#!/usr/bin/env python3
"""
Write frontend/src/utils/validationThresholds.ts from backend/app/core/config.py.

The browser pre-check repeats some of the server's admission thresholds so it
can warn before an upload. Those numbers used to be literals typed into
retinalValidator.ts, and they drifted: 256 px against the server's 480, a
0.60-1.70 aspect range against 0.65-1.65, and a foreground-coverage threshold
the browser never applied at all while reporting coverage as "within
thresholds". The browser now imports its thresholds from the file this script
generates, and a rule in the suite fails if that file differs from what this
script would write.

Usage:
    python backend/scripts/export_frontend_thresholds.py           # write the file
    python backend/scripts/export_frontend_thresholds.py --check   # exit 1 if it is stale

Reads config.py with the ast module (no application import, no dependencies).
"""
import ast
import os
import sys

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
CONFIG_PY = os.path.join(REPO_ROOT, "backend", "app", "core", "config.py")
TARGET = os.path.join(REPO_ROOT, "frontend", "src", "utils", "validationThresholds.ts")

# setting name -> what the browser uses it for
EXPORTED = (
    ("MIN_IMAGE_DIMENSION", "Gate 1: minimum width and height in pixels"),
    ("MAX_UPLOAD_SIZE_MB", "Gate 1: maximum upload size in megabytes"),
    ("RETINAL_MIN_COVERAGE", "Gate 2: minimum foreground (aperture) coverage, as a fraction of the frame"),
    ("RETINAL_RED_RATIO_MIN", "Gate 2: minimum red/blue channel ratio"),
    ("RETINAL_RED_SHARE_MIN", "Gate 2: minimum red share of the mean RGB"),
)


def config_defaults():
    """{setting: literal default} for every annotated assignment with a literal value."""
    with open(CONFIG_PY, encoding="utf-8") as fh:
        tree = ast.parse(fh.read())
    out = {}
    for node in ast.walk(tree):
        if isinstance(node, ast.AnnAssign) and isinstance(node.target, ast.Name) and node.value is not None:
            try:
                out[node.target.id] = ast.literal_eval(node.value)
            except (ValueError, SyntaxError):
                pass
    return out


def render():
    cfg = config_defaults()
    lines = [
        "// GENERATED by backend/scripts/export_frontend_thresholds.py from",
        "// backend/app/core/config.py. Do not edit by hand: a rule in the suite fails",
        "// if this file differs from the generator's output. The server re-checks",
        "// every image with the same settings and is the only authority.",
        "",
    ]
    for name, purpose in EXPORTED:
        if name not in cfg:
            raise SystemExit("config.py has no literal default for %s" % name)
        value = cfg[name]
        lines.append("/** %s */" % purpose)
        lines.append("export const %s = %s;" % (name, repr(value)))
        lines.append("")
    return "\n".join(lines)


def main():
    text = render()
    if "--check" in sys.argv[1:]:
        current = open(TARGET, encoding="utf-8").read() if os.path.exists(TARGET) else ""
        if current.replace("\r\n", "\n") != text:
            print("validationThresholds.ts is stale; run this script without --check")
            return 1
        print("validationThresholds.ts matches config.py")
        return 0
    with open(TARGET, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(text)
    print("wrote", os.path.relpath(TARGET, REPO_ROOT))
    return 0


if __name__ == "__main__":
    sys.exit(main())
