// GENERATED by backend/scripts/export_frontend_thresholds.py from
// backend/app/core/config.py. Do not edit by hand: a rule in the suite fails
// if this file differs from the generator's output. The server re-checks
// every image with the same settings and is the only authority.

/** Gate 1: minimum width and height in pixels */
export const MIN_IMAGE_DIMENSION = 480;

/** Gate 1: maximum upload size in megabytes */
export const MAX_UPLOAD_SIZE_MB = 15;

/** Gate 2: minimum foreground (aperture) coverage, as a fraction of the frame */
export const RETINAL_MIN_COVERAGE = 0.2;

/** Gate 2: minimum red/blue channel ratio */
export const RETINAL_RED_RATIO_MIN = 1.15;

/** Gate 2: minimum red share of the mean RGB */
export const RETINAL_RED_SHARE_MIN = 0.36;
